version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angular",
    "vue"
  ]
  environment = [
    "nodejs",
    "mongo"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"